manifest:
  defaults:
    remote: urob
    revision: v0.3 # Pin everything to v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: Good-Great-Grand-Wonderful
      url-base: https://github.com/Good-Great-Grand-Wonderful

  projects:
    - name: zmk
      remote: zmkfirmware
      #remote: urob
      #revision: v0.2+fix-child-nodes
      # revision: main
      import: app/west.yml
    - name: zmk-leader-key
      remote: urob
      path: modules/zmk/zmk-leader-key
    - name: zmk-helpers
      remote: urob
      path: modules/zmk/zmk-helpers
    - name: zmk-auto-layer
      remote: urob
      path: modules/zmk/zmk-auto-layer
    - name: zmk-adaptive-key
      remote: urob
      path: modules/zmk/zmk-adaptive-key
    - name: zmk-tri-state
      remote: urob
      path: modules/zmk/zmk-tri-state
    - name: zmk-unicode
      path: modules/zmk/unicode
    - remote: Good-Great-Grand-Wonderful
      name: gggw-zmk-keebs
      revision: zephyr-4.1
      import: config/west.yml
      clone-depth: 1

        # Temporarily overload Zephyr until
      # https://github.com/zmkfirmware/zephyr/pull/40 is merged.
    - name: zephyr
      revision: v4.1.0+zmk-fixes
      remote: zmkfirmware
      clone-depth: 1
      #import:
        # Only enable most commonly used boards. For less common hardware one
        # may need to enable additional modules.
        #name-allowlist:
        #  - cmsis
        #  - hal_nordic
        #  - hal_rpi_pico
        #  - hal_stm32
        #  - lvgl
        #  - tinycrypt
  self:
    path: config
