manifest:
  defaults:
    remote: urob
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: Good-Great-Grand-Wonderful
      url-base: https://github.com/Good-Great-Grand-Wonderful
    - name: efogdev
      url-base: https://github.com/efogdev
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: caksoylar
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-leader-key
      remote: urob
      path: modules/zmk/zmk-leader-key
    - name: zmk-helpers
      remote: urob
      path: modules/zmk/zmk-helpers
    - name: zmk-auto-layer
      remote: urob
      path: modules/zmk/zmk-auto-layer
    - name: zmk-adaptive-key
      remote: urob
      path: modules/zmk/zmk-adaptive-key
    - name: zmk-tri-state
      remote: urob
      path: modules/zmk/zmk-tri-state
    - name: zmk-unicode
      path: modules/zmk/unicode
    - name: gggw-zmk-keebs
      remote: Good-Great-Grand-Wonderful
      revision: zephyr-4.1
      path: modules/gggw-zmk-keebs
      import: config/west.yml
    - name: zmk-pmw3610-driver
      remote: efogdev
      revision: zephyr-4.1
      path: modules/zmk/zmk-pmw3610-driver
    - name: zmk-report-rate-limit
      remote: efogdev
      revision: main
      path: modules/zmk/zmk-report-rate-limit
    - name: zmk-input-processor-xyz
      remote: badjeff
      revision: main
      path: modules/zmk/zmk-input-processor-xyz
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
      path: modules/zmk/zmk-rgbled-widget
  self:
     path: config