#     keymap -c config/config_keymap-drawer.yaml parse -c 12 -z config/corne.keymap > keymap-drawer/corne.yaml
#     keymap -c config/config_keymap-drawer.yaml draw keymap-drawer/corne.yaml > keymap-drawer/corne.svg

# Example for using the keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch: {} # manual trigger only

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write # allow workflow to commit to the repo
    with:
      amend_commit: true
      keymap_patterns: "config/corne-42-simple.keymap config/crosses-42-simple.keymap"
      #config_path: "config/config_keymap-drawer.yaml" # config file, ignored if not exists
      output_folder: "keymap-drawer" # path to save produced SVG and keymap YAML files
      parse_args: "corne-42-simple:'--zmk-config config' crosses-42-simple:'--zmk-config config'" # use ZMK config for DTS parsing
      draw_args: "crosses-42-simple:'-k crosses/gggw_crosses_42_layout'" # specify layout for crosses
      west_config_path: 'config'
